In the callback for output(s):
  permissions-table.data
  permissions-data.data
  table-dropdown.options
  confirm-dialog.displayed
Output 3 (confirm-dialog.displayed) is already in use.
To resolve this, set `allow_duplicate=True` on
duplicate outputs, or combine the outputs into
one callback function, distinguishing the trigger
by using `dash.callback_context` if necessary.

In the callback for output(s):
  permissions-table.data
  permissions-data.data
  table-dropdown.options
  confirm-dialog.displayed
Output 2 (table-dropdown.options) is already in use.
To resolve this, set `allow_duplicate=True` on
duplicate outputs, or combine the outputs into
one callback function, distinguishing the trigger
by using `dash.callback_context` if necessary.

In the callback for output(s):
  permissions-table.data
  permissions-data.data
  table-dropdown.options
  confirm-dialog.displayed
Output 0 (permissions-table.data) is already in use.
To resolve this, set `allow_duplicate=True` on
duplicate outputs, or combine the outputs into
one callback function, distinguishing the trigger
by using `dash.callback_context` if necessary.
